version: '2'

services:
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - static_volume:/app/mercury/django_static
            - media_volume:/app/mercury/media
            - ./docker/nginx/pro:/etc/nginx/conf.d
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        depends_on: 
            - mercury
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"       

    mercury:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/mercury/Dockerfile
            args:
                GITHUB_TOKEN: ${GITHUB_TOKEN}
        entrypoint: /app/docker/mercury/entrypoint.sh
        volumes:
            - ${NOTEBOOKS_PATH}:/app/notebooks
            - static_volume:/app/mercury/django_static
            - media_volume:/app/mercury/media
        expose:
            - 8000     
        environment:
            DEBUG: ${DEBUG}
            SERVE_STATIC: ${SERVE_STATIC}
            DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
            DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
            DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
            SECRET_KEY: ${SECRET_KEY}
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}

volumes:
    static_volume: {}
    media_volume: {}