site_name: Mercury Docs
theme: readthedocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Get started: get-started.md
  - YAML parameters: yaml-parameters.md
  - Widgets: widgets.md
  - Output Files: output-files.md
  - Welcome Message: welcome.md
  - Embedding: embedding.md
  - Authentication: authentication.md
  - Admin Panel: admin-panel.md
  - Articles: articles.md
  - FAQ: faq.md
  - Commercial License: pro.md
  - Deploy: 
    - deploy/deployment.md
    - Deploy on Heroku: deploy/heroku.md
    - Deploy on Hugging Face: deploy/hugging-face-spaces.md
    - Deploy on AWS: deploy/aws.md
    - HTTPS Support: deploy/https-support.md
    
markdown_extensions:
  - markdown.extensions.admonition
  - toc:
      permalink: True